services:
  frontend:
    build:
      context: ./knowledgePulseFrontend
      dockerfile: Dockerfile
    container_name: knowledgePulse-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./knowledgePulseFrontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./knowledgePulseBackend
      dockerfile: Dockerfile
    container_name: knowledge-Pulse-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=knowledgePulse;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 2115@test
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - app-network

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - app-network
    command: >
      bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P '2115@test' -Q 'CREATE DATABASE knowledgePulse;' -C
      "

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "2115@test"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "2115@test", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mssql-data:
